### ISSUE TITLE
Membuat halaman dosen

### ISSUE THREAD

**Issue by VirgiFHermawan** [VirgiFHermawan/praktek-dts-01#1]
Buatlah halaman dosen menggunakan CI yang terdiri dari :
- Model
- View
- Controller

Pada setiap bagian harus diberikan identitas nama file, sebagai contoh model maka penamaan filenya adalah m_dosen.php

**Comment by DummyAccount-Virgi** [comment]
Pembuatan halaman untuk menampilkan data data dosen sudah selesai dibuat dan dilakukan push ke dalam main brach. terimakasih
